// lib/tasks.ts

import type { Task } from './types';

export const TASKS: Task[] = [
  // Pillar 1: Security & Trust (8 tasks)
  {
    id: 1,
    pillar: "1. Security & Trust",
    component: "Data Encryption",
    focus: "Implement TLS/SSL for all data in transit. Encrypt sensitive data at rest (e.g., PII, financial data) using AES-256.",
    tools: "AWS KMS, Azure Key Vault, Google Cloud KMS, Let's Encrypt",
    priority: "High",
    status: "Not Started",
    notes: "This is non-negotiable. One breach can end the company.",
  },
  {
    id: 2,
    pillar: "1. Security & Trust",
    component: "Authentication & Access",
    focus: "Implement Multi-Factor Authentication (MFA/2FA) via SMS, email, or authenticator app. Secure password storage (hashing & salting).",
    tools: "Auth0, Okta, Firebase Authentication, bcrypt",
    priority: "High",
    status: "Not Started",
    notes: "Use rate limiting to prevent brute-force attacks.",
  },
  {
    id: 3,
    pillar: "1. Security & Trust",
    component: "Secure Coding Practices",
    focus: "Protect against common vulnerabilities (OWASP Top 10: SQL Injection, XSS, etc.). Conduct regular code reviews and use static analysis tools.",
    tools: "Snyk, Veracode, SonarQube",
    priority: "High",
    status: "Not Started",
    notes: "",
  },
  {
    id: 4,
    pillar: "1. Security & Trust",
    component: "Regular Security Audits",
    focus: "Schedule periodic Vulnerability Assessment and Penetration Testing (VAPT). Obtain relevant certifications (e.g., ISO 27001, PCI-DSS if applicable).",
    tools: "Third-party cybersecurity firms, Cert-In empanelled auditors",
    priority: "High",
    status: "Not Started",
    notes: "Plan for this in your budget from day one.",
  },
  {
    id: 5,
    pillar: "1. Security & Trust",
    component: "API Security",
    focus: "Implement OAuth 2.0, JWT tokens, API rate limiting. Use CORS properly. Implement request signing and validation.",
    tools: "OAuth2, JWT, API Gateway (AWS/Azure/GCP)",
    priority: "High",
    status: "Not Started",
    notes: "APIs are common attack vectors for fintech apps.",
  },
  {
    id: 6,
    pillar: "1. Security & Trust",
    component: "Data Backup & Disaster Recovery",
    focus: "Set up automated daily/hourly backups. Test recovery procedures monthly. Maintain geographic redundancy.",
    tools: "AWS Backup, Azure Backup, Disaster Recovery as a Service (DRaaS)",
    priority: "High",
    status: "Not Started",
    notes: "Have a documented RTO and RPO strategy.",
  },
  {
    id: 7,
    pillar: "1. Security & Trust",
    component: "Incident Response Plan",
    focus: "Create incident response playbook. Define escalation procedures. Set up monitoring and alerting systems.",
    tools: "PagerDuty, Splunk, DataDog, ELK Stack",
    priority: "High",
    status: "Not Started",
    notes: "Response time can be the difference between a minor and major incident.",
  },
  {
    id: 8,
    pillar: "1. Security & Trust",
    component: "Third-party Risk Management",
    focus: "Audit third-party vendors and dependencies. Use Software Composition Analysis (SCA). Keep dependencies updated.",
    tools: "Dependabot, OWASP Dependency-Check, npm audit",
    priority: "Medium",
    status: "Not Started",
    notes: "Vendor breaches can compromise your security posture.",
  },

  // Pillar 2: Regulatory & Legal (9 tasks)
  {
    id: 9,
    pillar: "2. Regulatory & Legal",
    component: "Legal Framework & Licensing",
    focus: "Consult with fintech lawyer to identify required licenses (NBFC, PPI, etc.). Draft Terms of Service and Privacy Policy.",
    tools: "Legal counsel specializing in fintech, Company secretarial services",
    priority: "High",
    status: "Not Started",
    notes: "Regulations are complex and vary by product type.",
  },
  {
    id: 10,
    pillar: "2. Regulatory & Legal",
    component: "KYC / AML Compliance",
    focus: "Implement robust Customer Identification Program (CIP). Integrate digital KYC (Aadhaar, PAN verification).",
    tools: "Signzy, IDfy, Karza, DigiLocker APIs",
    priority: "High",
    status: "Not Started",
    notes: "Essential for preventing fraud and RBI/SEBI compliance.",
  },
  {
    id: 11,
    pillar: "2. Regulatory & Legal",
    component: "Data Privacy & Governance",
    focus: "Ensure compliance with DPDPA (India). Implement data residency/localization rules. Get user consent for data processing.",
    tools: "Internal data governance policies, AWS Mumbai region",
    priority: "High",
    status: "Not Started",
    notes: "Be transparent about what data you collect and why.",
  },
  {
    id: 12,
    pillar: "2. Regulatory & Legal",
    component: "Transaction Monitoring",
    focus: "Implement real-time transaction monitoring for suspicious activity. Set up alert thresholds for unusual patterns.",
    tools: "Featurespace, Kount, SAS Fraud Management",
    priority: "High",
    status: "Not Started",
    notes: "Required for AML compliance.",
  },
  {
    id: 13,
    pillar: "2. Regulatory & Legal",
    component: "Consumer Protection Act Compliance",
    focus: "Ensure compliance with Consumer Protection Act 2019. Set up grievance redressal mechanism. Document all transactions.",
    tools: "Internal CRM systems, Grievance management tools",
    priority: "High",
    status: "Not Started",
    notes: "Have clear processes for customer disputes.",
  },
  {
    id: 14,
    pillar: "2. Regulatory & Legal",
    component: "Tax Compliance",
    focus: "Implement GST compliance for your services. Maintain audit trails. Generate tax reports automatically.",
    tools: "Tally, Zoho Books, SAP Concur",
    priority: "Medium",
    status: "Not Started",
    notes: "Consult with a CA for tax implications.",
  },
  {
    id: 15,
    pillar: "2. Regulatory & Legal",
    component: "Contract Management",
    focus: "Standardize contracts with banks, payment partners, and customers. Use e-signature solutions.",
    tools: "DocuSign, Adobe Sign, LawRato",
    priority: "Medium",
    status: "Not Started",
    notes: "Clear contracts prevent disputes.",
  },
  {
    id: 16,
    pillar: "2. Regulatory & Legal",
    component: "Audit Trail & Record Keeping",
    focus: "Implement immutable audit logs for all transactions. Keep 7+ years of records. Use blockchain for sensitive records.",
    tools: "ELK Stack, AWS CloudTrail, Hyperledger Fabric",
    priority: "High",
    status: "Not Started",
    notes: "Regulatory authorities may ask for audits anytime.",
  },
  {
    id: 17,
    pillar: "2. Regulatory & Legal",
    component: "Cybersecurity Compliance",
    focus: "Meet NIST Cybersecurity Framework standards. Implement SOAR (Security Orchestration). Regular security trainings.",
    tools: "NIST CSF, Splunk SOAR, SecurityAwareness training",
    priority: "High",
    status: "Not Started",
    notes: "Proactive compliance reduces audit issues.",
  },

  // Pillar 3: Technology Stack (11 tasks)
  {
    id: 18,
    pillar: "3. Technology Stack",
    component: "Backend",
    focus: "Choose scalable, secure language/framework. Design microservices or monolithic architecture. Focus on reliability.",
    tools: "Node.js (Express), Python (Django), Java (Spring Boot)",
    priority: "High",
    status: "Not Started",
    notes: "Consider fintech-specific frameworks and libraries.",
  },
  {
    id: 19,
    pillar: "3. Technology Stack",
    component: "Frontend",
    focus: "Choose modern framework for responsive UI. Implement client-side validation. Optimize for performance.",
    tools: "React, Vue.js, Angular, Next.js",
    priority: "High",
    status: "Not Started",
    notes: "",
  },
  {
    id: 20,
    pillar: "3. Technology Stack",
    component: "Database",
    focus: "Select ACID-compliant database. Plan for scalability and backups. Implement data replication.",
    tools: "PostgreSQL, MySQL, AWS RDS, Google Cloud SQL",
    priority: "High",
    status: "Not Started",
    notes: "PostgreSQL is preferred for financial applications.",
  },
  {
    id: 21,
    pillar: "3. Technology Stack",
    component: "Cloud & DevOps",
    focus: "Set up CI/CD pipelines. Implement Infrastructure as Code (IaC). Set up logging and monitoring.",
    tools: "AWS, GCP, Azure, Docker, Kubernetes, Jenkins, Terraform",
    priority: "High",
    status: "Not Started",
    notes: "Good DevOps increases speed and reliability.",
  },
  {
    id: 22,
    pillar: "3. Technology Stack",
    component: "Message Queue & Event Streaming",
    focus: "Implement asynchronous processing for transactions. Use event-driven architecture for notifications.",
    tools: "RabbitMQ, Kafka, AWS SQS, Google Pub/Sub",
    priority: "High",
    status: "Not Started",
    notes: "Critical for handling high transaction volume.",
  },
  {
    id: 23,
    pillar: "3. Technology Stack",
    component: "Caching & Performance",
    focus: "Implement Redis/Memcached for caching. Optimize database queries. Use CDN for static assets.",
    tools: "Redis, Memcached, Cloudflare, AWS CloudFront",
    priority: "Medium",
    status: "Not Started",
    notes: "Fast response times improve user satisfaction.",
  },
  {
    id: 24,
    pillar: "3. Technology Stack",
    component: "Search & Analytics",
    focus: "Implement full-text search capabilities. Set up analytics pipeline. Use data warehousing.",
    tools: "Elasticsearch, Google BigQuery, Looker, Tableau",
    priority: "Medium",
    status: "Not Started",
    notes: "",
  },
  {
    id: 25,
    pillar: "3. Technology Stack",
    component: "Testing & QA",
    focus: "Implement unit, integration, and E2E testing. Use test automation. Aim for 80%+ code coverage.",
    tools: "Jest, Mocha, Selenium, Cypress, TestNG",
    priority: "High",
    status: "Not Started",
    notes: "Quality assurance is critical in fintech.",
  },
  {
    id: 26,
    pillar: "3. Technology Stack",
    component: "Monitoring & Logging",
    focus: "Set up real-time monitoring. Implement centralized logging. Create dashboards for visibility.",
    tools: "DataDog, New Relic, Splunk, ELK Stack, Prometheus",
    priority: "High",
    status: "Not Started",
    notes: "You can't fix what you can't see.",
  },
  {
    id: 27,
    pillar: "3. Technology Stack",
    component: "API Management",
    focus: "Implement API versioning. Set up API documentation (OpenAPI/Swagger). Manage API keys and rate limits.",
    tools: "Kong, AWS API Gateway, Azure API Management, Swagger",
    priority: "High",
    status: "Not Started",
    notes: "Good API management ensures developer experience.",
  },
  {
    id: 28,
    pillar: "3. Technology Stack",
    component: "Mobile Development",
    focus: "Choose React Native or native development. Ensure offline capabilities. Implement biometric authentication.",
    tools: "React Native, Flutter, iOS/Android native SDKs",
    priority: "Medium",
    status: "Not Started",
    notes: "Most fintech users access via mobile.",
  },

  // Pillar 4: User Experience (UX/UI) (8 tasks)
  {
    id: 29,
    pillar: "4. User Experience (UX/UI)",
    component: "UI Design & Branding",
    focus: "Create clean, professional design system. Ensure accessibility (WCAG standards). Build component library.",
    tools: "Figma, Sketch, Adobe XD, Storybook",
    priority: "Medium",
    status: "Not Started",
    notes: "Good design builds user trust.",
  },
  {
    id: 30,
    pillar: "4. User Experience (UX/UI)",
    component: "UX Flow & Onboarding",
    focus: "Map simple, frictionless user journeys. Design quick onboarding. Minimize form fields.",
    tools: "Miro, Whimsical, UserTesting, Hotjar",
    priority: "High",
    status: "Not Started",
    notes: "Complicated onboarding causes major user drop-off.",
  },
  {
    id: 31,
    pillar: "4. User Experience (UX/UI)",
    component: "Transparency & Trust",
    focus: "Clearly communicate fees, charges, interest rates. Provide easy-to-understand error messages. Detailed FAQs.",
    tools: "In-app calculators, knowledge base platforms, Zendesk",
    priority: "High",
    status: "Not Started",
    notes: "Avoid financial jargon. No hidden surprises.",
  },
  {
    id: 32,
    pillar: "4. User Experience (UX/UI)",
    component: "Accessibility & Inclusivity",
    focus: "Implement WCAG 2.1 AA compliance. Support screen readers. Ensure keyboard navigation. Multi-language support.",
    tools: "Axe DevTools, Lighthouse, Webaim, i18next",
    priority: "Medium",
    status: "Not Started",
    notes: "Accessibility benefits all users.",
  },
  {
    id: 33,
    pillar: "4. User Experience (UX/UI)",
    component: "Responsive Design",
    focus: "Ensure UI works on all devices (mobile, tablet, desktop). Test across browsers. Optimize for different screen sizes.",
    tools: "Chrome DevTools, BrowserStack, ResponsiveDesignChecker",
    priority: "High",
    status: "Not Started",
    notes: "",
  },
  {
    id: 34,
    pillar: "4. User Experience (UX/UI)",
    component: "User Feedback & Analytics",
    focus: "Implement in-app surveys. Track user behavior. Use heatmaps to identify friction points. Run A/B tests.",
    tools: "Amplitude, Mixpanel, Hotjar, Google Analytics 4",
    priority: "Medium",
    status: "Not Started",
    notes: "Data-driven decisions improve UX.",
  },
  {
    id: 35,
    pillar: "4. User Experience (UX/UI)",
    component: "Error Handling & Support",
    focus: "Design helpful error messages. Implement in-app help system. Create comprehensive support documentation.",
    tools: "Intercom, Drift, HubSpot, Zendesk",
    priority: "Medium",
    status: "Not Started",
    notes: "",
  },
  {
    id: 36,
    pillar: "4. User Experience (UX/UI)",
    component: "Performance Optimization",
    focus: "Optimize page load speed (target < 3 seconds). Minimize JavaScript. Use lazy loading. Implement service workers.",
    tools: "Lighthouse, WebPageTest, GTmetrix, Webpack",
    priority: "Medium",
    status: "Not Started",
    notes: "Fast apps improve user experience and SEO.",
  },

  // Pillar 5: Core Integrations (10 tasks)
  {
    id: 37,
    pillar: "5. Core Integrations",
    component: "Banking APIs",
    focus: "Connect to financial institutions securely. Use Account Aggregator framework. Fetch account statements and balances.",
    tools: "Account Aggregator (Sahamati), Setu, Finvu, BaaS platforms",
    priority: "High",
    status: "Not Started",
    notes: "AA framework is the future of financial data sharing in India.",
  },
  {
    id: 38,
    pillar: "5. Core Integrations",
    component: "Payment Gateways",
    focus: "Integrate reliable payment gateway for collections and disbursements. Support multiple payment methods.",
    tools: "Razorpay, PayU, Cashfree, Stripe, Square",
    priority: "High",
    status: "Not Started",
    notes: "Compare transaction rates (TDR) and features.",
  },
  {
    id: 39,
    pillar: "5. Core Integrations",
    component: "Communication APIs",
    focus: "Integrate transactional SMS, emails, push notifications. Support WhatsApp business messages.",
    tools: "Twilio, SendGrid, AWS SNS, Firebase Cloud Messaging, Gupshup",
    priority: "Medium",
    status: "Not Started",
    notes: "Essential for OTPs, transaction alerts, and notifications.",
  },
  {
    id: 40,
    pillar: "5. Core Integrations",
    component: "Identity Verification",
    focus: "Integrate Aadhaar eSign, PAN verification, GST verification. Implement liveness detection for KYC.",
    tools: "Aadhaar API, PAN API, Experian, Intellect IKYC",
    priority: "High",
    status: "Not Started",
    notes: "Automated verification speeds up onboarding.",
  },
  {
    id: 41,
    pillar: "5. Core Integrations",
    component: "Credit Bureau Integration",
    focus: "Integrate CIBIL/Equifax for credit score checks. Implement credit report fetching. Auto-decline based on rules.",
    tools: "CIBIL, Equifax, Experian, CibilScore APIs",
    priority: "High",
    status: "Not Started",
    notes: "Critical for lending decisions.",
  },
  {
    id: 42,
    pillar: "5. Core Integrations",
    component: "E-Signature & Document Management",
    focus: "Implement digital signatures for contracts. Store signed documents securely. Support audit trails.",
    tools: "DocuSign, Adobe Sign, eSignal",
    priority: "Medium",
    status: "Not Started",
    notes: "Legally binding in most jurisdictions.",
  },
  {
    id: 43,
    pillar: "5. Core Integrations",
    component: "GST & Tax Integration",
    focus: "Automate GST filing. Integrate with GSTIN verification. Support invoice generation and tax calculations.",
    tools: "GSTIN API, TaxCycle, Cleartax, Lybrate",
    priority: "Medium",
    status: "Not Started",
    notes: "",
  },
  {
    id: 44,
    pillar: "5. Core Integrations",
    component: "CRM Integration",
    focus: "Integrate with CRM for customer management. Sync customer data. Track interactions and communication.",
    tools: "Salesforce, HubSpot, Zoho CRM, Pipedrive",
    priority: "Low",
    status: "Not Started",
    notes: "",
  },
  {
    id: 45,
    pillar: "5. Core Integrations",
    component: "Email & Notification Service",
    focus: "Set up transactional email service. Implement email templates. Track delivery and opens.",
    tools: "SendGrid, Mailgun, AWS SES, Brevo",
    priority: "Medium",
    status: "Not Started",
    notes: "",
  },
  {
    id: 46,
    pillar: "5. Core Integrations",
    component: "Analytics & BI Integration",
    focus: "Send data to analytics platforms. Create business intelligence dashboards. Track KPIs automatically.",
    tools: "Google Analytics 4, Mixpanel, Amplitude, Tableau, Looker",
    priority: "Low",
    status: "Not Started",
    notes: "Later priority but important for growth.",
  },
];